spring:
  datasource:
    url: jdbc:sqlserver://acehawksvr3;databaseName=FNILP
    username: sa
    password: 123@ace
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    date-format: dd.MM.yyyy

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.SQLServer2012Dialect
  
server:
   port: ${PORT:8082} # This is the default port anyway, but you can change it here

   
farmerProductId: ISPRD003001000009376125072017
studentLifeProductId: ISPRD003001000000001116122019
publicTermLifeProductId: ISPRD0030001000000002131032013
groupLifeProductId: ISPRD0030001000000002431032013
shorttermLifeProductId: ISPRD003001000009589529032019
individualHealthProductId: ISPRD003001000009592523042019
groupHealthProductId: ISPRD003001000009592623042019
microHealthProductId: ISPRD003001000009592523042019
individualCriticalillnessProductID: ISPRD003001000009593527042019
groupCriticalillnessProductID: ISPRD003001000009593627042019
personalaccidentProductId: ISPRD003001000009375122062017
sportmanProductId: ISPRD0030001000000002331032013
snakeBiteProductId: ISPRD0030001000000002231032013


fileDir: D



security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  submitProposal: Create proposal and return proposal number
AgentController:
  agents: Get All Agents
BankController:
  banks: Get All Banks
BranchController:
  branches: Get All Branches
GradeController:
  grades: Get All Grades
CountryController:
  countrys: Get All Countries
CustomerController:
  customers: Get All Customers
HospitalController:
  hospitals: Get All Hospitals
OccupationController:
  occupations: Get All Occupations
OrganizationController:
  organizations: Get All Organizations
PaymentTypeController:
  paymentTypes: Get All Payment Types
ProvinceController:
  provinces: Get All Provinces
RelationshipController:
  relationships: Get All Relationships
SalemanController:
  salemans: Get All Sale Men
SalePointController:
  salepoints: Get All Sale points
SchoolController:
  schools: Get All Schools
TownshipController:
  townships: Get All Townships
ReligionController:
  religions: Get All Religions
QualificationController:
  qualifications: Get All Qualifications
TypeOfSportController:
  typeOfSports: Get All Type of sports
  
PolicyDataController:
  getPolicyData: Returns policy information

EndowmentLifeController:
  submitproposal: Create Endowment Life Proposal and return proposal number
GroupHealthController:
  submitproposal: Create Group Health Proposal and return proposal number
GroupCriticalIllnessController:
  submitproposal: Create Group Critical Illness Proposal and return proposal number
FarmerController:
  submitproposal: Create Farmer Life Proposal and return proposal number
GroupLifeController:
  submitproposal: Create Group Life Proposal and return proposal number
ShortTermEndowmentLifeController:
  submitproposal: Create Short Term Endowment Life proposal and return proposal number
StudentLifeController:
  submitproposal: Create Student Life proposal and return proposal number
BillCollectionController:
  payment: Create Subsequent Payment
SnakeBiteController:
  submitproposal: Create Snake Bite Life proposal and return proposal number
IndividualHealthController:
  submitproposal: Create Individual Health proposal and return proposal number
IndividualCriticalillnessController:
  submitproposal: Create Critical Illness proposal and return proposal number
MicroHealthController:
  submitproposal: Create Micro Health proposal and return proposal number
PersonalAccidentController:
  submitproposal: Create Personal Accident proposal and return proposal number
SportManController:
  submitproposal: Create Sportman proposal and return proposal number